keys:
  - &users:
    - &azmo age1aph83gkdg83l6cf83nsdthp95dcd5natpa7527sd3p8rtlcj3dgstl502c
    - &j525980 age1v8h3l9vwshd2wpf4ukd47yh2gxksyggpng92ggx0s6cqku2hypyq272ru3
  - &hosts:
    - &apollo age1qhde0et2q44sug4vfcgn7hee9lrm33fs4ex2xtre245e577dqpfsynrqe9
    - &hephaestus age19082075rmp926ajwg7ea4k0050tc4qvy7dtcehpe7hlvrdgr092qpkagqk
    - &artemis age1ugpqj4nfgvq00k62kw93medzqyk4c7xj5pdy580j2xmy9pfq99tse0f8cj
    - &workvm age13nje3juh4p823ww2vn0k225c64n45x4qveucxlhh00frp9xsjysqrjj4fy

creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
      - age:
          - *azmo
          - *apollo
          - *artemis
          - *hephaestus
          - *workvm
  - path_regex: hosts/common/users/azmo/secrets.ya?ml$
    key_groups:
      - age:
          - *azmo
          - *apollo
          - *artemis
          - *hephaestus
  - path_regex: hosts/common/users/j525980/secrets.ya?ml$
    key_groups:
      - age:
          - *j525980
          - *workvm
  - path_regex: hosts/apollo/secrets.ya?ml$
    key_groups:
      - age:
          - *azmo
          - *apollo
  - path_regex: hosts/artemis/secrets.ya?ml$
    key_groups:
      - age:
          - *azmo
          - *artemis
  - path_regex: hosts/hephaestus/secrets.ya?ml$
    key_groups:
      - age:
          - *azmo
          - *hephaestus
  - path_regex: hosts/work-vm/secrets.ya?ml$
    key_groups:
      - age:
          - *j525980
          - *workvm

  - path_regex: home/common/secrets.ya?ml$
    key_groups:
      - age:
          - *azmo
          - *j525980
  - path_regex: home/azmo/secrets.ya?ml$
    key_groups:
      - age:
          - *azmo
  - path_regex: home/azmo/features/email/secrets.ya?ml$
    key_groups:
      - age:
          - *azmo
  - path_regex: home/j525980/secrets.ya?ml$
    key_groups:
      - age:
          - *j525980
