keys:
  - &users:
    - &azmo age1aph83gkdg83l6cf83nsdthp95dcd5natpa7527sd3p8rtlcj3dgstl502c
  - &hosts:
    - &hephaestus age19082075rmp926ajwg7ea4k0050tc4qvy7dtcehpe7hlvrdgr092qpkagqk

creation_rules:
  - path_regex: hosts/hephaestus/secrets.ya?ml$
    key_groups:
    - age:
      - *azmo
      - *hephaestus

  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *azmo
      - *hephaestus

  - path_regex: home/azmo/secrets.ya?ml$
    key_groups:
    - age:
      - *azmo
      - *hephaestus
